# Generated by Django 5.2.10 on 2026-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Waakye Fest 2026', max_length=255)),
                ('date', models.CharField(default='Dec 24, 2026', max_length=100)),
                ('time', models.CharField(default='10:00 AM - 10:00 PM', max_length=100)),
                ('location', models.CharField(default='Ho Jubilee Park, Ho', max_length=255)),
            ],
        ),
    ]
