# Generated by Django 5.2.10 on 2026-01-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_eventsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='short_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
