# Generated by Django 5.2.10 on 2026-01-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Waakye Fest 2026', max_length=255)),
                ('date', models.CharField(default='Dec 24, 2026', max_length=100)),
                ('time', models.CharField(default='10:00 AM - 10:00 PM', max_length=100)),
                ('location', models.CharField(default='Ho Jubilee Park, Ho', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='EventSettings',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event'),
        ),
    ]
